apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: topolvmclusters.topolvm.cybozu.com
spec:
  preserveUnknownFields: false
  # group name to use for REST API: /apis/<group>/<version>
  group: topolvm.cybozu.com
  # list of versions supported by this CustomResourceDefinition
  versions:
  - name: v1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: false
    # Each version can define it's own schema when there is no top-level
    # schema is defined.
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              topolvmVersion:
                type: string
              deviceClasses:
                type: array
                nullable: false
                items:
                  type: object
                  properties:
                    nodeName:
                      type: string
                    classes:
                      type: array
                      nullable: false
                      items:
                        type: object
                        properties:
                          className:
                            type: string
                          volumeGroup:
                            type: string
                          default:
                            type: boolean
                          devices:
                            type: array
                            nullable: false
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                          spareGb:
                            type: integer
                            format: uint64
                          stripe:
                            type: integer
                            format: uint
                          stripeSize:
                            type: string
                            pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                        required:
                          - className
                          - volumeGroup
                          - devices
                  required:
                    - nodeName
                    - classes
            required:
              - topolvmVersion
              - deviceClasses
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  - name: v2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: TopolvmCluster is the Schema for the topolvmclusters API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TopolvmClusterSpec defines the desired state of TopolvmCluster
            properties:
              storage:
                properties:
                  className:
                    type: string
                  deviceClasses:
                    items:
                      properties:
                        classes:
                          items:
                            properties:
                              className:
                                type: string
                              default:
                                type: boolean
                              devices:
                                items:
                                  properties:
                                    auto:
                                      type: boolean
                                    name:
                                      type: string
                                    path:
                                      type: string
                                    size:
                                      format: int64
                                      type: integer
                                    type:
                                      type: string
                                  required:
                                    - name
                                    - type
                                  type: object
                                type: array
                              spareGb:
                                format: int64
                                type: integer
                              stripe:
                                type: integer
                              stripeSize:
                                type: string
                              volumeGroup:
                                type: string
                            required:
                              - className
                              - devices
                              - volumeGroup
                            type: object
                          type: array
                        nodeName:
                          type: string
                      required:
                        - classes
                        - nodeName
                      type: object
                    type: array
                  devices:
                    items:
                      properties:
                        auto:
                          type: boolean
                        name:
                          type: string
                        path:
                          type: string
                        size:
                          format: int64
                          type: integer
                        type:
                          type: string
                      required:
                        - name
                        - type
                      type: object
                    type: array
                  useAllDevices:
                    type: boolean
                  useAllNodes:
                    type: boolean
                  useLoop:
                    type: boolean
                  volumeGroupName:
                    type: string
                required:
                  - useLoop
                type: object
              topolvmVersion:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run "make" to regenerate code after modifying this file'
                type: string
            required:
              - storage
              - topolvmVersion
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
  conversion:
    # a Webhook strategy instruct API server to call an external webhook for any conversion between custom resources.
    strategy: Webhook
    # webhookClientConfig is required when strategy is `Webhook` and it configure the webhook endpoint to be
    # called by API server.
    webhook:
      # conversionReviewVersions indicates what ConversionReview versions are understood/preferred by the webhook.
      # The first version in the list understood by the API server is sent to the webhook.
      # The webhook must respond with a ConversionReview object in the same version it received.
      conversionReviewVersions: [ "v1","v2"]
      clientConfig:
        service:
          namespace: crd-conversion-webhook
          name: crd-conversion-webhook
          path: /crdconvert
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EUXpNREF6TURZeU1Wb1hEVE14TURReU9EQXpNRFl5TVZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjZCCml5Ri8zMjFyNlJQcjY0M3Nob0VKUjRTVEE0UGROYXdIMVRyVC9RU1MrSEdBUVJVTVc2RzVFa0oycFdnSXhDaGsKa0ZrSUc2TjhWU2FqSkpLeHJMcFhvQXgrdTFhOUF5ajJCMUp1am9kZFZmVGpVaHpwNU9pdHNkNWNaNXV0alBEVgowMno4UExaRGJWQUg5MGJHZitCdEg4cjdvM3ZOb0VXY0QxeHZuckNjK0hPS3JoUTBFOUJORkk5V01UdE9Ta0s1CjJSM3FHUGVkeHJxSVQ5V0JWUTlzeVd3d3dyeDBQcnJ6Z0JYNlJzUklCcHJCMlFobUs3UjEwNzB3a0dEQkE1U2cKcFp1RDE1NlNpSkY5bkgxWWJsRXVyR2xXOEU3NU4wZmtWa1paRzJTQXU2ZUlJbzU3MDI5SERSLys1TU9zUU5SWQpwTmVmVDJjWk42QVhyZWMwamtNQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZIOFk2RjZ6MXZOY3dmY0RoeHZGT2p2cGM5TnBNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBcmZ0UjlhbXI3ZVJmbU84Y3B4V0Mxd2ZkQmlmWXJJZDRBNVRnMXZkcmpSVmJXOFRIQQpZZDJYdzJ4cW1jZlliOGlGSkpLVW9DRElzaHFMK09GSU55NTVpMTRKdGNLNDBDV3poQVhDSzNqM2FhU2hGNitLCkRhcjFQUWZSUVZzMHFUR0NOVmZvQUx3MW1XTTVOVGttVGs3QW5yak1FRGR2SWNrNklMdWFFS2ZMN0dUV0FDeGIKSzM4aGlOcGQ2SnJ1OUdrZlZVUVo2ZlBDaHhtN0k1Rlkzazh1dGJPYXN3bkh3SE1KWGxqdUZQZ0xaL2dOL08yQQpwYWRoVFdoUlo5cGY1emJZdGxFWnU1dGpuZ3RhTDhFT1pXZEM4RmlsblM5RWZwaGpwaWFzbXN1QXBDcU1GNytxCnBVZnMvSklLSUtIYjVKMkIxQ0IwS05yd3hKenN0d3dJUU1vSgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlGTGpDQ0JCYWdBd0lCQWdJU0E1UVlYT1poeG5mQ0JkU2hxM1dCYTdRNk1BMEdDU3FHU0liM0RRRUJDd1VBCk1ESXhDekFKQmdOVkJBWVRBbFZUTVJZd0ZBWURWUVFLRXcxTVpYUW5jeUJGYm1OeWVYQjBNUXN3Q1FZRFZRUUQKRXdKU016QWVGdzB5TVRBMU1Ua3dPREk1TWpOYUZ3MHlNVEE0TVRjd09ESTVNak5hTUI4eEhUQWJCZ05WQkFNTQpGQ291WTNBdGFXNTBMbTE1WVd4aGRXUmhMbU51TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCCkNnS0NBUUVBdlZTSU9xUWxIdS9naDh1Mm92VDRmd2thRHRFaFFLTW5ia2dKUUhRQ0VpZTVzR1F0UkxsUHNLUncKSHRhWUFzcW5TK3lUdDNoMHcwd2l3YlBDSWdPdExyNE9WVGtrc1hnSVl2dDZLbWhoODRQY1RhY29mRHh1L3dYNgo2RFJGM3cvVTZUSmRtVGorekZ3REU1RmpFNEw5SHJ6M0Q0NHZvL1VwM1RIMDRDYTMvZWVpdTFqeUtjWVU1QVdCClY5akI2T3JQOCtKRWR2Y0RUd3R0VGV0c1o4TGN1cFVJVC9kWDhhU1NUejE2VnY5cWZadTJBeW1QRGh1L2F1azQKUmI1ZzdmaDJldFJ3dG9PWXkwd0ZwemRpWGd1TnVQc2RPTW5mUkFTOGxRanBCVzVkbkVUTmE0dXAyUStRMlV2VQpoVnVPTzZrZ1RLOXFrV1Vxek9neWtVY0JKY0VXV1FJREFRQUJvNElDVHpDQ0Frc3dEZ1lEVlIwUEFRSC9CQVFECkFnV2dNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUEKTUIwR0ExVWREZ1FXQkJSUS9nZVo3MGhXOExTbjVZcy8xYmV3bkZOMVV6QWZCZ05WSFNNRUdEQVdnQlFVTHJNWAp0MWhXeTY1UUNVRG1INitkaXhUQ3hqQlZCZ2dyQmdFRkJRY0JBUVJKTUVjd0lRWUlLd1lCQlFVSE1BR0dGV2gwCmRIQTZMeTl5TXk1dkxteGxibU55TG05eVp6QWlCZ2dyQmdFRkJRY3dBb1lXYUhSMGNEb3ZMM0l6TG1rdWJHVnUKWTNJdWIzSm5MekFmQmdOVkhSRUVHREFXZ2hRcUxtTndMV2x1ZEM1dGVXRnNZWFZrWVM1amJqQk1CZ05WSFNBRQpSVEJETUFnR0JtZUJEQUVDQVRBM0Jnc3JCZ0VFQVlMZkV3RUJBVEFvTUNZR0NDc0dBUVVGQndJQkZocG9kSFJ3Ck9pOHZZM0J6TG14bGRITmxibU55ZVhCMExtOXlaekNDQVFRR0Npc0dBUVFCMW5rQ0JBSUVnZlVFZ2ZJQThBQjIKQUc5VGRxd3g4REVaMkprQXBGRVYvM2NWSEJIWkFzRUFLUWFOc2dpYU45a1RBQUFCZVlQMVU3b0FBQVFEQUVjdwpSUUlnRzg2ODZpMXY2WnJKR1hLcWM5WEZpQzRKT2FVNFFNZXNUSVgvNEExV0o2Y0NJUUNjWGpGOElKSUxFRGN4CkNaWGlmWkR5Y3FoY3JLRXRLNlJaMi9zYmRCemN0d0IyQVBaY2xDL1JkekFpRkZRWUNEQ1VWbzdqVFJNWk03L2YKREM4Z0M4eE84V1RqQUFBQmVZUDFVN1FBQUFRREFFY3dSUUlnYVlKMTN5MmRISTNCVE03b1pyTDlLQVc4Q3pBbwo1NXZWQWxaaExNS0x3dVVDSVFENTVOeFBkT2JZS1d3NUFDRW9MOXV6amtxSllRcFhjdFpyZGE4VHhPNmt2VEFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVZKdzJyeTRiSFliWThCL0hvRVd1elJuajN1MWJ5aE5VUE01a0VFZ2UKV3QrRkd0Z1hUUDJZdTQvMmpVZU1qNlZNQWFSdCtTcVBTWE5LRzhPbktLMWFISmxtNVYyRTdESjNKN1NyMVNGQgoxOGdnYjFERFp4QnJKRnFIaEU4MEhSOHQ2SnIzQ1llY1hzRVRiVGVVbmxvb3BueVB2c0wrSDNtVXoyNHhpNVJhCnl1V0Z1VzJzNE4yekdlY3N6U2ZobFdaNkpqN3kra3pZUWJWMjFXMlkyTEJYOTBVRTVGejFDbGY2U21QdlRCeWEKZ1BPelpvdFlzTkdCeXkrTjRYT1pGWmVRQkYxZlovN2lxVmZuMFRLL29PMnlaRlJmRkpjZWtHR2hsTjlJUWNOdwo5eG15NlorSHMwbm4vRExkSWNvMWNiTG9QUyt2OEpQMTZmNmFvUzQ0R3NnNGhBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRkZqQ0NBdjZnQXdJQkFnSVJBSkVyQ0VyUERCaW5VL2JXTGlXblgxb3dEUVlKS29aSWh2Y05BUUVMQlFBdwpUekVMTUFrR0ExVUVCaE1DVlZNeEtUQW5CZ05WQkFvVElFbHVkR1Z5Ym1WMElGTmxZM1Z5YVhSNUlGSmxjMlZoCmNtTm9JRWR5YjNWd01SVXdFd1lEVlFRREV3eEpVMUpISUZKdmIzUWdXREV3SGhjTk1qQXdPVEEwTURBd01EQXcKV2hjTk1qVXdPVEUxTVRZd01EQXdXakF5TVFzd0NRWURWUVFHRXdKVlV6RVdNQlFHQTFVRUNoTU5UR1YwSjNNZwpSVzVqY25sd2RERUxNQWtHQTFVRUF4TUNVak13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM3QWhVb3pQYWdsTk1QRXV5TlZaTEQrSUx4bWFaNlFvaW5YU2FxdFN1NXhVeXhyNDVyK1hYSW85Y1AKUjVRVVZU
  scope: Namespaced
  names:
    kind: TopolvmCluster
    listKind: TopolvmClusterList
    plural: topolvmclusters
    singular: topolvmcluster
