apiVersion: v1
data:
  check-ready.sh: |
    #!/bin/sh
    while true
    do
      status=`kubectl -n "${NAME_SPACE}" get topolvmclusters.topolvm.cybozu.com topolvmcluster-sample -o jsonpath='{.status.phase}'`
      if [ "$status" = "Ready" ];then
        exit
      fi
      sleep 10
    done
kind: ConfigMap
metadata:
  name: check-ready